language: node_js
node_js:
  - "iojs"
  - "7"
cache: yarn
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get -qq update
  - sudo apt-get install imagemagick --fix-missing